project:
  type: website
  output-dir: docs

website:
  title: "Aurélie Blumenfeld"
  favicon : favicon_AB.png
  navbar:
    title: false
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me

format:
  html:
    theme: 
      - cosmo        # ← thème de base obligatoire
      - styles.scss  # ← tes personnalisations par dessus
    mainfont: Montserrat 
    toc: true
    page-layout: full



