project:
  type: website
  output-dir: docs
  resources: 
    - CV_aurelieblumenfeld.pdf

website:
  title: "Aurélie Blumenfeld"
  favicon : favicon_AB.png
  navbar:
    title: false
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects

format:
  html:
    theme: 
      - cosmo        # ← thème de base obligatoire
      - styles.scss  # ← tes personnalisations par dessus
    css: styles.css
    mainfont: Montserrat 
    toc: false
    page-layout: full



